version: '3'
services:
  openbanking:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - '27017:27017'