version: '3'
services:
  driveright-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - '27017:27017'