version: '3'
services:
  console:
    image: nodesource/nsolid-console
    container_name: nsolid.console
    ports:
      - 9001:9001
      - 9002:9002
      - 9003:9003
      - 6753:6753
    environment:
      - NSOLID_CONSOLE_LICENSE_KEY=847ebce2-269e-482f-b6bc-969c19a619a1
  openbanking:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 3000:3000
      - 9229:9229
    environment:
      - NSOLID_APPNAME=lendable
      - NSOLID_COMMAND=console:9001
      - NSOLID_DATA=console:9002
      - NSOLID_BULK=console:9003
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    depends_on:
      - mongodb
      - console
  mongodb:
    image: mongo
    ports:
      - '27017:27017'